os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
bundler_args: --without development
addons:
  code_climate:
    repo_token: 7af99d9225b4c14640f9ec3cb2e24d2f7103ac49417b0bd989188fb6c25f2909
after_success:
    - bundle exec codeclimate-test-reporter
